"""02_order_date

Revision ID: 75581122486d
Revises: 7ef0cd10f3ac
Create Date: 2023-05-04 18:04:57.457355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "75581122486d"
down_revision = "7ef0cd10f3ac"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "orders_delivery_schedule",
        sa.Column("date", sa.DateTime(), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("orders_delivery_schedule", "date")
    # ### end Alembic commands ###
