"""01_initial

Revision ID: 7ef0cd10f3ac
Revises: 
Create Date: 2023-05-04 17:34:52.378201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7ef0cd10f3ac"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "couriers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "courier_type",
            sa.Enum("FOOT", "BIKE", "AUTO", name="courier_types"),
            nullable=False,
        ),
        sa.Column("regions", sa.ARRAY(sa.Integer()), nullable=False),
        sa.Column("working_hours", sa.ARRAY(sa.String()), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "orders",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("courier_id", sa.Integer(), nullable=True),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.Column("regions", sa.Integer(), nullable=False),
        sa.Column("delivery_hours", sa.ARRAY(sa.String()), nullable=False),
        sa.Column("cost", sa.Float(), nullable=False),
        sa.Column("completed_time", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["courier_id"],
            ["couriers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "orders_delivery_schedule",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("courier_id", sa.Integer(), nullable=False),
        sa.Column("order_id", sa.Integer(), nullable=False),
        sa.Column("group_order_id", sa.Integer(), nullable=False),
        sa.Column("group_time", sa.DateTime(), nullable=True),
        sa.Column("group_weight", sa.Float(), nullable=False),
        sa.Column("group_cost", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["courier_id"],
            ["couriers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("orders_delivery_schedule")
    op.drop_table("orders")
    op.drop_table("couriers")
    # ### end Alembic commands ###
