"""02_orders

Revision ID: 908764ee59ad
Revises: b3940d4dcaeb
Create Date: 2023-04-26 18:26:44.640607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "908764ee59ad"
down_revision = "b3940d4dcaeb"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "orders",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("courier_id", sa.Integer(), nullable=True),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.Column("regions", sa.Integer(), nullable=False),
        sa.Column("delivery_hours", sa.ARRAY(sa.String()), nullable=False),
        sa.Column("cost", sa.Float(), nullable=False),
        sa.Column("completed_time", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["courier_id"],
            ["couriers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("orders")
    # ### end Alembic commands ###
